---
- name: Shut down a node
  hosts: node1  # Replace 'node1' with the actual target node(s) if different
  become: yes   # Use 'become' if root privileges are required
  tasks:
    - name: Shut down the node
      ansible.builtin.shell: /sbin/shutdown now
      ignore_errors: yes  # Optional: This prevents failures from stopping playbook execution
